---
title: "FAQ: Wie poole ich mein $R^2$
richtig über mehrere (bspw. 15) Imputationen?"
author: NA
categories: [FAQ]
---

### a. Methode nach Harel (2009)

Die von Harel (2009) vorgeschlagene Methode beinhaltet mehrere Schritte:\
1. Die Quadratwurzel aus $R^2$ ziehen\
2. eine Fisher *z*-Transformation durchführen, damit der Wertebereich auf alle reellen Zahlen ausgeweitet wird\
3. Rubins Regeln für metrische Variablen anwenden\
4. mit einer inversen *z*-Transformation den Wert wieder zurückrechnen und quadrieren

Harel, O. (2009). The estimation of R2 and adjusted R2 in incomplete data sets using multiple imputation. *Journal of Applied Statistics, 36*(10), 1109-1118.

### b. pool.R2() aus eatRep

Im Paket eatRep kann das über die Funktion `pool.R2()` berechnet werden. Die Funktion wird momentan noch nicht auf den Namensraum (Namespace) des Pakets exportiert, was allerdings ab der nächsten Paketversion möglich sein wird.

Angenommen, aus einer Analyse multipel imputierter Daten resultieren 5 verschiedene (hier fiktive) $R^2$-Werte, dann kann der gepoolte $R^2$-Wert folgendermaßen bestimmt werden:

```{r eval = FALSE}
r2 <- c(0.12,0.18,0.17,0.21,0.23)
eatRep::pool.R2(r2)
```

##

Weitere Fragen und/oder deren Antworten können abgelegt und eingesehen werden unter: t:/SIG/SIG Methoden/Liste methodischer Fragen.docx
