---
title: "eatRep"
---

# Info

```{r, echo=FALSE}
#3
ansprech_rep <- "Sebastian Weirich, Benjamin Becker"
version_rep <- "[CRAN page](https://cran.r-project.org/web/packages/eatRep/index.html)"
quelle_rep <- "[CRAN page](https://cran.r-project.org/web/packages/eatRep/index.html)"
descFunktion_rep <- "Berechnet Mittelwerte, Standardabweichungen, Varianzen, Häufigkeitstabellen, Perzentile und lineare (logistische) Regressionen sowie Trends für alle diese Analysen in geclusterten Mehrebenenstrukturen mit imputierten Daten. Das Paket implementiert einen Teil der Funktionsweise der Computersoftware WesVar in R und ist im Wesentlichen für die IQB-Bildungstrendstudien relevant."

info_rep <- data.frame(ansprech_rep, version_rep, quelle_rep)
colnames(info_rep) <- c("contact", "latest version", "source")

knitr::kable(info_rep)
```

### Description

Calculates means, standard deviations, variances, frequency tables, percentiles and linear (logistic) regressions, as well as trends for all these analyses in clustered multilevel structures with imputed data. The package implements part of the functionality of the WesVar computer software in R and is mainly relevant for the IQB Bildungstrend studies.

### Documentation

1) A vignette which demonstrates replication analyses with eatRep is [here](https://cran.r-project.org/web//packages/eatRep/vignettes/eatRep.html).
2) The internal structure of the package is documented [here](https://github.com/iqb-research/IQB-Methods/blob/main/_site/structure.html). This overview is primarily dedicated to developers who want to further improve or extend the package and therefore need to understand its structure. 
3) Workshop materials concerning `eatRep` can also be found on the IQB network drives: `i:\Methoden\02_IQB-interne_eat_Workshops\eatRep_2021\`

