---
title: "IQB Methods Team"
---

Currently, this website hosts material for and from the R-SIG. It might be expanded later on to include general methods team related material.

## Navigation

At the top bar you'll find more Info on R-SIG and you can find our Newsletter (to be done). Just click on it to read more.

On the left side you'll find tutorials and information regarding R and Quarto. You can find some introductions to R (in German and English), the IQB specific eat-packages, and more. Some explanations are right here on this page, for others you can find links to other pages.

On the right side you can see where you are right now. 

The search bar is in the upper right corner. 

## R-SIG

::: callout-tip
The R-SIG meets each every two weeks on Monday from 13:00 - 14:00. The next meeting will be on 9.10.2023.
:::

In this meeting we talk about all kind of topics related to scientific programming in R. Come along!

## Schedule

| Date      | Topic                                                          |
|----------------------------------|-------------------------------------|
| 9.10.2023 | Improving code: How to write clear and parsimonious code in R? |
