---
title: "Help"
editor_options: 
  chunk_output_type: console
---

## Contact for eat Packages

:::: nav-pills
::: panel-tabset
## BT Shiny App
| Contact | Email |
|------------------------------------|------------------------------------|
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |

## eatAnalysis

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |
| [Sebastian Weirich](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/17/) | sebastian.weirich\[at\]iqb.hu-berlin.de |
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |

## eatArchive

| Contact | Email |
|------------------------------------|------------------------------------|
| [Janine Buchholz](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/13/) | janine.buchholz\[at\]iqb.hu-berlin.de |

## eatATA

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatAutoCode

| Contact | Email |
|------------------------------------|------------------------------------|
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |
| [Kristoph Schumann](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/46/) | kristoph.schumann\[at\]iqb.hu-berlin.de |
| [Jakob Schäfer](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/bistatest/64/) | jakob.schaefer\[at\]iqb.hu-berlin.de |

## eatCodebook

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatDataTest

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatDB

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatFDZ

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatGADS

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatGets

| Contact | Email |
|------------------------------------|------------------------------------|
| [Annegret Rucker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/fdz/29/) | annegret.rucker\[at\]iqb.hu-berlin.de |

## eatMap

| Contact | Email |
|------------------------------------|------------------------------------|
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |

## eatModel

| Contact | Email |
|------------------------------------|------------------------------------|
| [Sebastian Weirich](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/17/) | sebastian.weirich\[at\]iqb.hu-berlin.de |

## eatPlot

| Contact | Email |
|------------------------------------|------------------------------------|
| [Nicklas Hafiz](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/73/) | nicklas.jakob.hafiz\[at\]hu-berlin.de |

## eatPrep

| Contact | Email |
|------------------------------------|------------------------------------|
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |

## eatPrepTBA

| Contact | Email |
|------------------------------------|------------------------------------|
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |
| [Kristoph Schumann](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/46/) | kristoph.schumann\[at\]iqb.hu-berlin.de |
| [Jakob Schäfer](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/bistatest/64/) | jakob.schaefer\[at\]iqb.hu-berlin.de |

## eatRecode

| Contact | Email |
|------------------------------------|------------------------------------|
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |
| [Nicklas Hafiz](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/73/) | nicklas.jakob.hafiz\[at\]hu-berlin.de |

## eatRep

| Contact | Email |
|------------------------------------|------------------------------------|
| [Sebastian Weirich](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/17/) | sebastian.weirich\[at\]iqb.hu-berlin.de |
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |

## eatTools

| Contact | Email |
|------------------------------------|------------------------------------|
| [Sebastian Weirich](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/17/) | sebastian.weirich\[at\]iqb.hu-berlin.de |
| [Benjamin Becker](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/7/) | b.becker\[at\]iqb.hu-berlin.de |
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |

## eatWidget

| Contact | Email |
|------------------------------------|------------------------------------|
|NN|-|
| [Karoline Sachse](https://www.iqb.hu-berlin.de/de/institut/ueber-uns/personen/methoden/63/) | karoline.sachse\[at\]iqb.hu-berlin.de |

:::
::::


```{=html}
<!-- 

## FAQ

<details>

<summary>Question 1</summary>

Some example answer.

</details>

## Current Issues on Github

link to github issues? 
like this one? https://github.com/iqb-research/IQB-Methods/issues
-->
```
