---
title: "eatPlot"
author: Nicklas Hafiz
description: "Creating plots from the eatRep output (main use: Bildungstrend)."
image: eatPlot.svg
#image-alt: eatPlot Sticker, several paint brushes in a glass before a red background
---

[bookmark link](https://nickhaf.github.io/eatPlot/)

# Info

```{r, echo=FALSE}
#11
ansprech_plot <- "Nicklas Hafiz, Philipp Franikowski"
version_plot <- "[DESCRIPTION on github](https://github.com/nickhaf/eatPlot/blob/main/DESCRIPTION)"
quelle_plot <- "[github page](https://github.com/nickhaf/eatPlot)"

descFunktion_plot <- "Creating plots from the eatRep output (main use: Bildungstrend)."

info_plot <- data.frame(ansprech_plot, version_plot, quelle_plot)
colnames(info_plot) <- c("contact", "latest version", "source")

knitr::kable(info_plot)
```

### Description

Creating plots from the eatRep output (main use: Bildungstrend).

**Dokumentation:**

```{r, echo=FALSE}
# **Documentation:** [Info page with several vignettes](https://nickhaf.github.io/eatPlot/)
doku_plot <- "[Info page with several vignettes](https://nickhaf.github.io/eatPlot/)"

table <- data.frame(doku_plot, check.rows = FALSE)
colnames(table) <- "Documentation"

knitr::kable(table)
```
